title: 用Vscode写笔记
description: 我的知乎文章专栏 - 记录一些Vscode 笔记插件的方法
show_downloads: false
logo: /assets/logo.jpg
google_analytics:
#theme: jekyll-theme-minimal
# theme: minima
# minima:
#   skin: dark

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
